// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartWaterBillingSystem.Infrastructure.Data.Context;

#nullable disable

namespace SmartWaterBillingSystem.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SmartWaterBillingSystemDbContext))]
    [Migration("20260329183327_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("InvoiceNumbersSequence");

            modelBuilder.Entity("SmartWaterBillingSystem.Domain.Entities.Invoice", b =>
                {
                    b.Property<string>("InvoiceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(10)")
                        .HasDefaultValueSql("FORMAT(NEXT VALUE FOR InvoiceNumbersSequence, '0000000000')");

                    b.Property<int>("AmountOfConsumption")
                        .HasColumnType("int");

                    b.Property<int>("CurrentConsumptionAmount")
                        .HasColumnType("int");

                    b.Property<string>("FiscalYear")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<DateTime>("FromTheDateOf")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FromTheDateTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("HouseType")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoicesNote")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PreviousConsumptionAmount")
                        .HasColumnType("int");

                    b.Property<bool>("SanitationIsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("ServiceFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SubscriberNumber")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("SubscriptionNumber")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<decimal>("TaxFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TaxValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TheValueOfWaterConsumption")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalBill")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalInvoice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WasteWaterConsumptionValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("InvoiceNumber");

                    b.HasIndex("HouseType");

                    b.HasIndex("SubscriberNumber");

                    b.HasIndex("SubscriptionNumber");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("SmartWaterBillingSystem.Domain.Entities.SlideDistribution", b =>
                {
                    b.Property<string>("SlideNumber")
                        .HasColumnType("char(1)");

                    b.Property<int>("AmountExpenditureSlide")
                        .HasColumnType("int");

                    b.Property<string>("HouseType")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<decimal>("PricePerCubicMeterOfWater")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("PriceServiceSewage")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("SlideDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SlideDistributionNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SlideNumber");

                    b.HasIndex("HouseType");

                    b.ToTable("SlideDistributions");
                });

            modelBuilder.Entity("SmartWaterBillingSystem.Domain.Entities.Subscriber", b =>
                {
                    b.Property<string>("PersonalIDNumber")
                        .HasColumnType("char(10)");

                    b.Property<string>("SubscriberArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubscriberGovernorate")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubscriberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubscriberNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubscriberPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonalIDNumber");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("SmartWaterBillingSystem.Domain.Entities.Subscription", b =>
                {
                    b.Property<string>("SubscriptionNumber")
                        .HasColumnType("char(10)");

                    b.Property<string>("HouseType")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<bool>("IsThereSanitation")
                        .HasColumnType("bit");

                    b.Property<string>("SubscriberNumber")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("SubscriptionNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TheLastReadingOfTheMeter")
                        .HasColumnType("int");

                    b.Property<int>("TheNumberOfFloorsOfTheHouse")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionNumber");

                    b.HasIndex("HouseType");

                    b.HasIndex("SubscriberNumber");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("SmartWaterBillingSystem.Domain.Entities.TypesOfRealEstate", b =>
                {
                    b.Property<string>("HouseType")
                        .HasColumnType("char(1)");

                    b.Property<string>("TypesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TypesNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("HouseType");

                    b.ToTable("TypesOfRealEstates");
                });

            modelBuilder.Entity("SmartWaterBillingSystem.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("SmartWaterBillingSystem.Domain.Entities.TypesOfRealEstate", "RealEstateType")
                        .WithMany()
                        .HasForeignKey("HouseType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaterBillingSystem.Domain.Entities.Subscriber", "Subscriber")
                        .WithMany()
                        .HasForeignKey("SubscriberNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaterBillingSystem.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Invoices")
                        .HasForeignKey("SubscriptionNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RealEstateType");

                    b.Navigation("Subscriber");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SmartWaterBillingSystem.Domain.Entities.SlideDistribution", b =>
                {
                    b.HasOne("SmartWaterBillingSystem.Domain.Entities.TypesOfRealEstate", "TypesOfRealEstate")
                        .WithMany()
                        .HasForeignKey("HouseType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypesOfRealEstate");
                });

            modelBuilder.Entity("SmartWaterBillingSystem.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("SmartWaterBillingSystem.Domain.Entities.TypesOfRealEstate", "TypesOfRealEstate")
                        .WithMany()
                        .HasForeignKey("HouseType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWaterBillingSystem.Domain.Entities.Subscriber", "Subscriber")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriberNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subscriber");

                    b.Navigation("TypesOfRealEstate");
                });

            modelBuilder.Entity("SmartWaterBillingSystem.Domain.Entities.Subscriber", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SmartWaterBillingSystem.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
